server:
  port: 9095
  
spring:
  cloud:
    gateway:
      routes:
      - id: admin-service
        uri:
          lb://admin-service
        predicates:
        - Path=/api/v1/admin/**
      - id: recommendation-service
        uri:
          lb://recommendation-service
        predicates:
        - Path=/recommendFood/**
      - id: fav-food-service
        uri:
          lb://fav-food-service
        predicates:
        - Path=/favfood/**
  application:
    name: cloud-gateway  
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
jwt:
  secret: Covid19
  token:
    validity: 5000
    
    